site_name: Plugin Docs
theme:
  name: material
  language: ja
  logo: null
  icon:
    repo: fontawesome/brands/git-alt
  features:
    - navigation.tabs
    - content.code.copy
  palette:
    - scheme: default
      primary: green
      accent: light green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: green
      accent: light green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
nav:
  - Home: index.md
  - List: 
    - List: list/index.md
    - Main: list/main.md
    - Res : list/res.md
    - Lobby: list/lobby.md
  - Add Docs: how-to-add.md
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
plugins:
  - search:
      lang: ja
  - i18n:
      docs_structure: folder
      languages:
        - locale: ja
          default: true
          name: 日本語
          build: true
repo_url: https://github.com/morinoparty/documentation
repo_name: Plugin Documentation
copyright: No Rights Reserved. CC0
